spring:
  datasource:
    url: jdbc:mysql://localhost:3306/meow1?serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
    context-path: /api
  jwt:
    secret-key: c3ByaW5nU2VjdXJpdHlKd3RQcmFjdGljZUtleUphbmdKam9sa2l
kakao:
  client-id: faf26a5a6001ba7f6b3cd14f9fbc1d26
  redirect-uri: https://www.meowng.com/redirect
  token-uri: https://kauth.kakao.com/oauth/token
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID:}
      secret-key: ${AWS_SECRET_ACCESS_KEY:}
    region:
      static: ap-northeast-2
    s3:
      bucket: s3-an2-image-meowng
    stack:
      auto: false